title: Troubleshoot
description: Notes about AI, ML and development
theme: just-the-docs

url: https://EveSa.github.io/Troubleshoot

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/EveSa.github.io/Troubleshoot
